server:
  port: 80
spring:
  application:
    name: service-customer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms
feign:
  hystrix:
    enabled: true  # 开启Feign的熔断功能
