server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: service-eureka