server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://120.78.67.244:3306/user-center?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 159263
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.dhcc.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka